{% set version = "0.1.3" %}

package:
  name: annsel
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/a/annsel/annsel-{{ version }}.tar.gz
  sha256: 6ef0341057f57a93294bec98ab8f4aef83be67ea280389b544ad668b220fbb04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anndata
    - more-itertools >=10.7
    - narwhals >=2.14
    - pooch >=1.8.2
    - session-info2
    - tqdm >=4
    - universal-pathlib >=0.2

test:
  imports:
    - annsel
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/srivarra/annsel
  summary: A Narwhals powered DataFrame-style selection, filtering and indexing operations on AnnData Objects.
  doc_url: https://annsel.readthedocs.io/
  dev_url: https://github.com/srivarra/annsel
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - srivarra
